[package]
edition.workspace = true
name = "llmx-feedback"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
llmx-protocol = { workspace = true }
sentry = { version = "0.34" }
tracing-subscriber = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
